# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d964df3363d3366d8850a46d0a9bebc4658d808fe4be45981f066c550e5d0344158021361c30112d55aeb326cd12f1fe7c4657de34f305c37ef8b1f059fd41

test:
  secret_key_base: 1a73c5dd1a7c6d9cfe7d0c4fbf2ad305cad35b34588f755956fbdc6075061c5384de6f94003c4d143f00a31c67b45177c6119214c3af34384960450c04258f7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
